# Generated by Django 5.0.6 on 2024-07-03 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careprovider',
            old_name='speciality',
            new_name='specialty',
        ),
    ]
